import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Link
          href="/"
          className="fixed left-0 top-0 flex w-full justify-starttext-2xl text-white pb-6 pt-8 backdrop-blur-2x"
        >
          PokeMon Finder&nbsp;
        </Link>
        {children}
      </body>
    </html>
  );
}
